export function PrintFooter({ note }: { note?: string | null }) {
  return (
    <div className="mt-10 hidden items-center justify-between border-t border-slate-300 pt-3 text-[10px] text-slate-500 print:flex">
      <span>Generated by CivFlow</span>
      {note && <span>{note}</span>}
    </div>
  );
}
